### ISSUE TITLE
Missing Episodes

### ISSUE THREAD

**Issue by gelsas** [flownzu/TraktTV-UpdateClient#21]
Hello again,

thanks for making the new .exe so fast.

I would like to ask if you could add a missing episodes feature.

What I mean is the possiblity to have a list of missing episodes which maybe can be exported to a txt or csv file.

I am searching for a while now for an application, which can simply show me a list of episodes I am missing.  (Because sometimes I think I only miss 1-2 episodes of a show but going through my whole library manually would take long)

cheers, gelsas

**Comment by flownzu** [comment]
![Preview](https://user-images.githubusercontent.com/18683325/46163301-1b5b2180-c28b-11e8-9a14-b84059742251.PNG)

Would this TreeView be alright? I can do export to csv if you want, doesn't take much time to implement.

**Comment by gelsas** [comment]
That would be perfect!

How would the exported format look like then ?
something like this ? TVSHOW,SEASON,EPISODE

Or how would you format it?

**Comment by flownzu** [comment]
Yeah show name, season number, episode number was the plan. If you want it another way you can tell me.

**Comment by gelsas** [comment]
Great, I have one small addition.

Also could you make it maybe that way if a whole season is missing to add a checkbox or something

Where you can check export season as
TVSHOW,SEASON 

but when that option is not checked it exports every episodes of that season in 
TVSHOW,SEASON,EPISODE 
format.

**Comment by flownzu** [comment]
Something like this?
![Test](https://user-images.githubusercontent.com/18683325/46165095-07fe8500-c290-11e8-90da-98fab8fd6eff.PNG)

**Comment by gelsas** [comment]
Yes Looks perfect!
Could you maybe add Show Season and Episode in the first line?

Like this: https://i.imgur.com/pk2jINV.png

**Comment by flownzu** [comment]
Yeah that's already added just doesn't show on the picture.
I added a new Button in the main window under the refresh button where you can access this feature.

New release [**here**](https://github.com/flownzu/TraktTV-UpdateClient/releases/tag/v1.1.1.2).
