### ISSUE TITLE
Missing Episodes not behaving completly correct

### ISSUE THREAD

**Issue by gelsas** [flownzu/TraktTV-UpdateClient#22]
First of all thanks a lot for implementing my request for a feature so fast, really awesome!

Just tried the feature it shows the not yet watched episodes as it seems.

Maybe it was a misunderstanding, I was hoping for it to show me the episodes I do not have collected yet.

Sorry for asking so much, thanks again for the patience with me

**Comment by flownzu** [comment]
At the moment this tool is only for managing the watch list, I will see what I can do for collection.

**Comment by flownzu** [comment]
Can you try out the [new build](
https://github.com/flownzu/TraktTV-UpdateClient/releases/tag/v1.1.1.2a) and report back if the problem is fixed?

**Comment by gelsas** [comment]
Works perfectly! Thanks alot!
